# Generated by Django 4.1 on 2023-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0005_job_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobchoice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="jobmcqoneanswer",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="jobmcqoneanswer",
            name="jobanswer_ptr",
        ),
        migrations.RemoveField(
            model_name="mcqoneanswer",
            name="answer_ptr",
        ),
        migrations.RemoveField(
            model_name="mcqoneanswer",
            name="choice",
        ),
        migrations.AlterField(
            model_name="jobquestion",
            name="technique",
            field=models.CharField(
                choices=[
                    ("text", "Text based answer"),
                    ("file_upload", "File Upload answer"),
                    ("pre_verified", "Auto Upload answer"),
                ],
                max_length=55,
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="JobChoice",
        ),
        migrations.DeleteModel(
            name="JobMcqOneAnswer",
        ),
        migrations.DeleteModel(
            name="McqOneAnswer",
        ),
    ]
