# Generated by Django 4.1 on 2023-01-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpanel",
            "0007_remove_adhaarfile_file_remove_birthcertificate_file_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Adhaar",
        ),
    ]
