# Generated by Django 4.1 on 2023-01-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0008_delete_adhaar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adhaarfile",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="birthcertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="castecertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="disabilitycertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="domicilecertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="hsc",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="incomecertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="jeeallotmentletter",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="jeemarksheet",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="medicalcertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="migrationcertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="nationalitycertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="pan",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="passport",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="sportscertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="ssc",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.RenameField(
            model_name="transfercertificate",
            old_name="PrivateKey",
            new_name="IPFS_Key",
        ),
        migrations.AddField(
            model_name="adhaarfile",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="adhaarfile",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="castecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="castecertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="disabilitycertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="disabilitycertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="domicilecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="domicilecertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="hsc",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="hsc",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="incomecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="incomecertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jeeallotmentletter",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="jeeallotmentletter",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jeemarksheet",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="jeemarksheet",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="medicalcertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="medicalcertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="migrationcertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="migrationcertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="nationalitycertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="nationalitycertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="pan",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="pan",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="passport",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="passport",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sportscertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="sportscertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="ssc",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="ssc",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="transfercertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AddField(
            model_name="transfercertificate",
            name="Private_key",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
