# Generated by Django 4.1 on 2022-12-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_initial"),
        ("userpanel", "0007_alter_submitpreverifiedquestion_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitfilequestion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="adminpanel.form"
            ),
        ),
        migrations.AlterField(
            model_name="submitpreverifiedquestion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="adminpanel.form"
            ),
        ),
    ]
