# Generated by Django 4.1 on 2022-12-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0003_delete_category_alter_documentmodel_adhaarfile_and_more"),
        ("userpanel", "0008_alter_submitfilequestion_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitpreverifiedquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.question"
            ),
        ),
    ]
