# Generated by Django 4.1 on 2023-01-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0010_submittextquestion_form_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobsubmitfilequestion",
            name="form",
        ),
        migrations.RemoveField(
            model_name="jobsubmitpreverifiedquestion",
            name="form",
        ),
        migrations.RemoveField(
            model_name="jobsubmittextquestion",
            name="form",
        ),
    ]
