# Generated by Django 4.1 on 2023-01-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0011_remove_jobsubmitfilequestion_form_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submitfilequestion",
            name="form",
        ),
        migrations.RemoveField(
            model_name="submitpreverifiedquestion",
            name="form",
        ),
        migrations.RemoveField(
            model_name="submittextquestion",
            name="form",
        ),
    ]
