# Generated by Django 4.1 on 2023-01-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="adhaar_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
    ]
