from django.contrib import admin

from adminpanel.models import *

admin.site.register(PersonalDetails)
admin.site.register(SSC)
admin.site.register(HSC)
admin.site.register(MigrationCertificate)
admin.site.register(JEEmarksheet)
admin.site.register(JEEallotmentLetter)
admin.site.register(DisabilityCertificate)
admin.site.register(CasteCertificate)
admin.site.register(DomicileCertificate)
admin.site.register(PAN)
admin.site.register(BirthCertificate)
admin.site.register(Passport)
admin.site.register(SportsCertificate)
admin.site.register(TransferCertificate)
admin.site.register(IncomeCertificate)
admin.site.register(MedicalCertificate)
admin.site.register(NationalityCertificate)
admin.site.register(DocumentModel)
admin.site.register(Question)
admin.site.register(JobQuestion)
admin.site.register(Form)
admin.site.register(Job)
admin.site.register(Adhaar)
admin.site.register(AdhaarFile)
